services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: finance-ledger_db
      POSTGRES_USER: finance-ledger
      POSTGRES_PASSWORD: finance-ledger
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U finance-ledger -d finance-ledger_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./init-keycloakDB.sql:/docker-entrypoint-initdb.d/init-keycloakDB.sql
  keycloak:
    image: quay.io/keycloak/keycloak:26.4.7
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    depends_on:
      - postgres
  backend-app:
    image: finance-ledger-app:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - finance-ledger-app:1.0.0
    environment:
      DB_NAME: finance-ledger_db
      DB_HOST: postgres
      DB_USER: finance-ledger
      DB_PASSWORD: finance-ledger
      KEYCLOAK_HOST: keycloak
      KEYCLOAK_PORT: 8080
      REALM: finance
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started