spring:
  application:
    name: finance-ledger

  # Database configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:finance-ledger_db}
    username: ${DB_USER:finance-ledger}
    password: ${DB_PASSWORD:finance-ledger}
    jpa:
      hibernate:
        ddl-auto: update
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
  # Security Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8081}/realms/${REALM:finance}

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /finance-ledger

# Management Endpoints
management:
  endpoint:
    refresh:
      access: read_only
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: refresh,health,metrics
